<?php
/**
 * Member-only access to the exchange-rates page.
 *
 * Authentication is deliberately delegated to WordPress rather than to a
 * password stored in the theme. The capability below is assigned only to the
 * shared member account during deployment (see docs/member-exchange-access.md).
 * This keeps password hashes in WordPress' user table and makes password
 * rotation possible without a code release.
 *
 * @package KAAO
 */

defined( 'ABSPATH' ) || exit;

const KAAO_EXCHANGE_RATES_SLUG       = 'exchange-rates';
const KAAO_EXCHANGE_RATES_CAPABILITY = 'kaao_view_exchange_rates';
const KAAO_MEMBER_LOGIN_PATH          = 'member-login';
const KAAO_MEMBER_LOGIN_QUERY_VAR     = 'kaao_member_login';

/**
 * Return whether the current visitor may view exchange-rate content.
 */
function kaao_can_view_exchange_rates(): bool {
	return is_user_logged_in()
		&& ( current_user_can( KAAO_EXCHANGE_RATES_CAPABILITY ) || current_user_can( 'manage_options' ) );
}

/**
 * Build the branded member-login URL.
 *
 * @param string $redirect_to URL to visit after login.
 */
function kaao_member_login_url( string $redirect_to = '' ): string {
	$login_url = home_url( '/' . KAAO_MEMBER_LOGIN_PATH . '/' );
	if ( '' !== $redirect_to ) {
		$login_url = add_query_arg( 'redirect_to', $redirect_to, $login_url );
	}

	return $login_url;
}

/**
 * Return whether a URL points to the protected exchange-rates page.
 *
 * @param string $url Candidate URL.
 */
function kaao_is_exchange_rates_url( string $url ): bool {
	$target_path = trailingslashit( (string) wp_parse_url( home_url( '/' . KAAO_EXCHANGE_RATES_SLUG . '/' ), PHP_URL_PATH ) );
	$url_path    = trailingslashit( (string) wp_parse_url( $url, PHP_URL_PATH ) );

	return $target_path === $url_path;
}

/**
 * Replace a wp-login.php URL generated by core or another plugin when its
 * return destination is the protected page. This is a safety net for code
 * which calls wp_login_url() before this theme's template_redirect handler.
 *
 * @param string $login_url    Default WordPress login URL.
 * @param string $redirect     Requested post-login URL.
 * @param bool   $force_reauth Whether to force reauthentication.
 */
function kaao_exchange_rates_login_url( string $login_url, string $redirect, bool $force_reauth ): string {
	if ( $redirect && kaao_is_exchange_rates_url( $redirect ) ) {
		return kaao_member_login_url( $redirect );
	}

	return $login_url;
}
add_filter( 'login_url', 'kaao_exchange_rates_login_url', 99, 3 );

/**
 * Catch direct redirects to wp-login.php that did not use the login_url
 * filter, while leaving all other WordPress login flows unchanged.
 *
 * @param string $location Redirect destination.
 * @param int    $status   HTTP status.
 */
function kaao_exchange_rates_login_redirect( string $location, int $status ): string {
	$login_path = (string) wp_parse_url( wp_login_url(), PHP_URL_PATH );
	if ( (string) wp_parse_url( $location, PHP_URL_PATH ) !== $login_path ) {
		return $location;
	}

	$query       = wp_parse_url( $location, PHP_URL_QUERY );
	$query_args  = is_string( $query ) ? wp_parse_args( $query ) : array();
	$redirect_to = isset( $query_args['redirect_to'] ) ? (string) $query_args['redirect_to'] : '';

	return kaao_is_exchange_rates_url( $redirect_to ) ? kaao_member_login_url( $redirect_to ) : $location;
}
add_filter( 'wp_redirect', 'kaao_exchange_rates_login_redirect', 99, 2 );

/**
 * Make /member-login/ a theme-owned endpoint, even when no WordPress page has
 * been created for it. This avoids falling back to wp-login.php because a page
 * was unpublished, assigned the wrong template, or omitted during deployment.
 *
 * @param WP $wp WordPress request object.
 */
function kaao_register_member_login_request( WP $wp ): void {
	if ( is_admin() || wp_doing_ajax() || trim( $wp->request, '/' ) !== KAAO_MEMBER_LOGIN_PATH ) {
		return;
	}

	unset( $wp->query_vars['error'] );
	$wp->query_vars[ KAAO_MEMBER_LOGIN_QUERY_VAR ] = '1';
}
add_action( 'parse_request', 'kaao_register_member_login_request' );

/**
 * Register the virtual route flag so WordPress retains it in the main query.
 *
 * @param string[] $vars Public query variables.
 * @return string[]
 */
function kaao_member_login_query_vars( array $vars ): array {
	$vars[] = KAAO_MEMBER_LOGIN_QUERY_VAR;

	return $vars;
}
add_filter( 'query_vars', 'kaao_member_login_query_vars' );

/**
 * @return bool Whether the current request is the branded member login route.
 */
function kaao_is_member_login_request(): bool {
	return '1' === (string) get_query_var( KAAO_MEMBER_LOGIN_QUERY_VAR ) || is_page( KAAO_MEMBER_LOGIN_PATH );
}

/**
 * Keep the virtual login route from being converted to a WordPress 404.
 *
 * @param bool|null $preempt Whether another callback already handled the request.
 * @return bool|null
 */
function kaao_member_login_prevent_404( $preempt ) {
	return kaao_is_member_login_request() ? true : $preempt;
}
add_filter( 'pre_handle_404', 'kaao_member_login_prevent_404' );

/**
 * Render the KAAO login template for the route regardless of page records or
 * page-template metadata stored in the database.
 *
 * @param string $template Resolved WordPress template.
 */
function kaao_member_login_template( string $template ): string {
	if ( kaao_is_member_login_request() ) {
		return KAAO_DIR . '/page-templates/member-login.php';
	}

	return $template;
}
add_filter( 'template_include', 'kaao_member_login_template', 99 );

/**
 * Add a dedicated body class for the branded login layout.
 *
 * @param string[] $classes Existing body classes.
 * @return string[]
 */
function kaao_member_login_body_class( array $classes ): array {
	if ( kaao_is_member_login_request() ) {
		$classes[] = 'kaao-member-login-page';
	}

	return $classes;
}
add_filter( 'body_class', 'kaao_member_login_body_class' );

/**
 * Return whether a page is the protected exchange-rates page.
 *
 * @param int|WP_Post|null $page Page object or ID. Defaults to the queried page.
 */
function kaao_is_exchange_rates_page( $page = null ): bool {
	if ( null === $page ) {
		return is_page( KAAO_EXCHANGE_RATES_SLUG );
	}

	$page = get_post( $page );

	return $page instanceof WP_Post
		&& 'page' === $page->post_type
		&& KAAO_EXCHANGE_RATES_SLUG === $page->post_name;
}

/**
 * Stop intermediary caches and search engines from retaining protected output.
 */
function kaao_exchange_rates_private_headers(): void {
	nocache_headers();
	header( 'X-Robots-Tag: noindex, nofollow, noarchive', true );
}

/**
 * Require authentication and the dedicated capability before rendering the page.
 */
function kaao_protect_exchange_rates_page(): void {
	if ( ! kaao_is_exchange_rates_page() ) {
		return;
	}

	kaao_exchange_rates_private_headers();

	if ( kaao_can_view_exchange_rates() ) {
		return;
	}

	if ( ! is_user_logged_in() ) {
		$login_url = kaao_member_login_url( (string) get_permalink( get_queried_object_id() ) );
		wp_safe_redirect( $login_url );
		exit;
	}

	wp_die(
		esc_html__( 'Your account does not have permission to view the exchange rates.', 'kaao' ),
		esc_html__( 'Access denied', 'kaao' ),
		array( 'response' => 403 )
	);
}
add_action( 'template_redirect', 'kaao_protect_exchange_rates_page', 9 );

/**
 * Authenticate submissions from the branded Member Login page.
 *
 * Authentication continues to use WordPress' password hashing, cookies and
 * authentication filters; this only replaces the wp-login.php presentation.
 */
function kaao_handle_member_login(): void {
	if ( ! kaao_is_member_login_request() || ! isset( $_POST['kaao_member_login_submit'] ) ) {
		return;
	}

	$redirect_to = isset( $_POST['redirect_to'] ) ? wp_unslash( $_POST['redirect_to'] ) : '';
	$redirect_to = wp_validate_redirect( (string) $redirect_to, home_url( '/exchange-rates/' ) );
	$login_url   = kaao_member_login_url( $redirect_to );

	if ( ! isset( $_POST['kaao_member_login_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['kaao_member_login_nonce'] ) ), 'kaao_member_login' ) ) {
		wp_safe_redirect( add_query_arg( 'login', 'invalid-request', $login_url ) );
		exit;
	}

	$credentials = array(
		'user_login'    => sanitize_user( wp_unslash( $_POST['log'] ?? '' ) ),
		'user_password' => (string) wp_unslash( $_POST['pwd'] ?? '' ),
		'remember'      => ! empty( $_POST['rememberme'] ),
	);
	$user        = wp_signon( $credentials, is_ssl() );

	if ( is_wp_error( $user ) || ! user_can( $user, KAAO_EXCHANGE_RATES_CAPABILITY ) ) {
		if ( ! is_wp_error( $user ) ) {
			wp_logout();
		}
		wp_safe_redirect( add_query_arg( 'login', 'failed', $login_url ) );
		exit;
	}

	wp_safe_redirect( $redirect_to );
	exit;
}
add_action( 'template_redirect', 'kaao_handle_member_login', 8 );

/**
 * Add a noindex directive when the protected page is rendered by WordPress.
 *
 * @param array<string, string> $robots Robots directives.
 * @return array<string, string>
 */
function kaao_exchange_rates_robots( array $robots ): array {
	if ( kaao_is_exchange_rates_page() ) {
		$robots['noindex']  = true;
		$robots['nofollow'] = true;
	}

	return $robots;
}
add_filter( 'wp_robots', 'kaao_exchange_rates_robots' );

/**
 * Reject direct REST requests for the protected page before the controller
 * prepares its content. This protects /wp-json/wp/v2/pages/<id> as well as
 * the equivalent ?rest_route= request.
 *
 * @param mixed           $result  Existing result.
 * @param WP_REST_Server  $server  REST server.
 * @param WP_REST_Request $request Current request.
 * @return mixed
 */
function kaao_protect_exchange_rates_rest( $result, WP_REST_Server $server, WP_REST_Request $request ) {
	if ( kaao_can_view_exchange_rates() ) {
		return $result;
	}

	$route = $request->get_route();
	if ( 1 !== preg_match( '#^/wp/v2/pages/(\d+)$#', $route, $matches ) ) {
		return $result;
	}

	if ( ! kaao_is_exchange_rates_page( (int) $matches[1] ) ) {
		return $result;
	}

	return new WP_Error(
		'kaao_exchange_rates_authentication_required',
		__( 'Authentication is required to view this resource.', 'kaao' ),
		array( 'status' => is_user_logged_in() ? 403 : 401 )
	);
}
add_filter( 'rest_pre_dispatch', 'kaao_protect_exchange_rates_rest', 10, 3 );

/**
 * Exclude the protected page from REST page collections, including requests
 * filtered by its slug. Singular requests are rejected above.
 *
 * @param array<string, mixed> $args    Query arguments.
 * @param WP_REST_Request      $request REST request.
 * @return array<string, mixed>
 */
function kaao_protect_exchange_rates_rest_collections( array $args, WP_REST_Request $request ): array {
	if ( kaao_can_view_exchange_rates() ) {
		return $args;
	}

	$page = get_page_by_path( KAAO_EXCHANGE_RATES_SLUG, OBJECT, 'page' );
	if ( ! $page instanceof WP_Post ) {
		return $args;
	}

	$excluded_posts   = isset( $args['post__not_in'] ) ? (array) $args['post__not_in'] : array();
	$excluded_posts[] = $page->ID;
	$args['post__not_in'] = array_unique( array_map( 'absint', $excluded_posts ) );

	return $args;
}
add_filter( 'rest_page_query', 'kaao_protect_exchange_rates_rest_collections', 10, 2 );

/**
 * Provision the shared member account via WP-CLI without putting its password
 * in source control. It is intentionally available only in the CLI context.
 */
function kaao_register_exchange_rates_member_cli_command(): void {
	if ( ! defined( 'WP_CLI' ) || ! WP_CLI || ! class_exists( 'WP_CLI' ) ) {
		return;
	}

	WP_CLI::add_command(
		'kaao exchange-member provision',
		static function ( array $args, array $assoc_args ): void {
			$password = getenv( 'KAAO_MEMBER_PASSWORD' );
			$email    = isset( $assoc_args['email'] ) ? sanitize_email( (string) $assoc_args['email'] ) : '';
			$reset    = isset( $assoc_args['reset-password'] ) && 'true' === $assoc_args['reset-password'];

			if ( ! is_string( $password ) || '' === $password ) {
				WP_CLI::error( 'Set KAAO_MEMBER_PASSWORD in the environment before provisioning the account.' );
			}

			if ( ! is_email( $email ) ) {
				WP_CLI::error( 'Pass a valid account email with --email=member@example.com.' );
			}

			$user = get_user_by( 'login', 'kaaomember' );
			if ( ! $user ) {
				$user_id = wp_insert_user(
					array(
						'user_login' => 'kaaomember',
						'user_pass'  => $password,
						'user_email' => $email,
						'role'       => 'subscriber',
					)
				);
				if ( is_wp_error( $user_id ) ) {
					WP_CLI::error( $user_id->get_error_message() );
				}
				$user = get_user_by( 'id', $user_id );
			} elseif ( $reset ) {
				wp_set_password( $password, $user->ID );
			}

			$user->add_cap( KAAO_EXCHANGE_RATES_CAPABILITY );
			WP_CLI::success( 'The kaaomember account can now view /exchange-rates/.' );
		}
	);
}
add_action( 'cli_init', 'kaao_register_exchange_rates_member_cli_command' );
